User.destroy_all
u1 = User.create :username => 'Cull', :email => 'hugo.cullinan@hotmail.com', :password => 'chicken'
u2 = User.create :username => 'Chump', :email => 'chump@ga.co', :password => 'chicken'
puts "#{ User.count } users created."

Recipe.destroy_all
r1 = Recipe.create :dish => 'Toast', :image => 'https://www.simplyrecipes.com/wp-content/uploads/2010/01/cinnamon-toast-horiz-a-1800.jpg', :serves => 1, :time => 5, :ingredients => ['bread', 'spread', 'butter'], :method => ['put bread in toaster', 'spread butter on toasted bread', 'spread your preferred spread on buttered toast']
r2 = Recipe.create :dish => 'Bacon and egg roll', :image => "https://d3lp4xedbqa8a5.cloudfront.net/s3/digital-cougar-assets/food/2015/03/18/40dc1f506d414c2a99e11de113fa05c3/bacon-and-egg-roll-with-herb-a-oli.jpg?width=768&height=639&mode=crop&quality=75&anchor=middlecenter", :serves  => 1, :time => 10, :ingredients => ['bun', 'sauce', 'spinach', 'egg', 'bacon'], :method => ['fry egg and bacon', 'toast bun while frying', 'add sauce to toasted bun', 'add spinach to top bun', 'add fried egg and bacon to bottom bun']
r3 = Recipe.create :dish => 'Weet-bix', :image => 'https://img.kidspot.com.au/I_04-8Jt/w643-h428-cfill-q90/kk/2018/10/weet-bix-banana-and-honey-recipe-506844-1.jpg', :serves => 1, :time => 2, :ingredients => ['weet-bix', 'milk', 'banana', 'honey'], :method => ['add preferred portion of weet-bix to bowl', 'drizzle honey', 'add sliced banana', 'add milk']
puts "#{ Recipe.count } recipes created."
r4 = Recipe.create :dish => 'Chilli Con Carne', :image => 'https://157212-453144-1-raikfcquaxqncofqfm.stackpathdns.com/wp-content/uploads/2019/03/chilli-con-carne-13.jpg', :serves => 8, :time => 15, :ingredients => ['2 tsp olive oil', '125g rindless bacon, rough chop', '750g lean beef mince', '2 medium brown onions, finely chopped', '2 medium red capsicums, chopped', '3 garlic cloves', '1 long red chilli chopped', '2 tbsp chilli powder', '800g can chopped tomatoes', '400g can red kidney beans', 'choice of garnish'], :method => ['Heat oil in a large saucepan over medium heat, Add bacon, Cook for 5 to 6 minutes or until crisp, Add mince, Cook, stirring with a wooden spoon to break up mince, for 15 minutes or until browned.',
"Add onions, capsicums, garlic and chopped chilli. Cook for 5 to 6 minutes or until vegetables are soft. Add chilli powder. Cook, stirring, for 1 minute or until fragrant.", 'Add tomatoes and 1 cup cold water. Bring to the boil. Reduce heat to mediumlow. Simmer, partially covered, for 30 minutes or until sauce has reduced slightly.', '
Add beans. Increase heat to medium. Cook for 15 minutes or until beans are heated through and sauce has thickened. Serve chilli with toppings.']
r5 = Recipe.create :dish => 'Chilli Prawn Linguine', :image => 'https://img.taste.com.au/oOvDMASb/w720-h480-cfill-q80/taste/2016/11/linguine-with-prawns-chilli-garlic-rocket-95151-1.jpeg', :serves => 4, :time => 15, :ingredients => ['340g linguine', '80ml olive oil', '2 garlic cloves, finely chopped', '1 large red chilli', '24 raw king prawns, peeled', 'basil', 'lemon'], :method => ['Step 1. Cook pasta until al dente', ' Step 2. Heat oil in pan, add chilli and garlic over a gentle heat for 30 seconds.', ' Step 3. Add the prawns and cook over a high heat, stirring frequently, for about 3 minutes', ' Step 4. Drain the pasta and add to the pan, give them a toss', ' Step 5. Toss the mixture with basil, salt and pepper', 'Serve with lemon wedge']
r6 = Recipe.create :dish => 'Mushroom Risotto', :image => 'https://hips.hearstapps.com/delish/assets/17/35/1504128527-delish-mushroom-risotto.jpg', :serves => 4, :time => 60, :ingredients => ['8 cups chicken stock', '1 tbsp. extra-virgin olive oil', '1 onion, finely chopped', '2 tbsp. butter, divided', '2 cloves garlic, minced', '1 lb. button mushrooms, sliced', '1 bay leaf', '4 sprigs thyme', '2 cups arborio rice', '1/2 cup white wine', '1 cup freshly grated Parmesan', '3/4 cup frozen peas, thawed', '2 tbsp. chopped fresh parsley'], :method => ['In a medium saucepan over medium heat, bring chicken broth to a simmer. Reduce heat to low.', 'In a large pot or Dutch oven, heat oil. Add onion and cook, stirring often, until translucent, about 5 minutes. Add 1 tablespoon butter, garlic, mushrooms, bay leaf and thyme. Cook until the mushrooms have softened and are golden, about 4 more minutes, then season with salt and pepper. Remove mixture from the pot.', 'Melt remaining tablespoon butter in the pot and add the arborio rice, stirring quickly. Cook until the grains are well-coated and smell slightly toasty, about 2 minutes. Add the wine and cook until the wine has mostly absorbed.', 'With a ladle, add about 1 cup hot broth. Stirring often, cook until the rice has mostly absorbed liquid. Add remaining broth about 1 cup at a time, continuing to allow the rice to absorb each addition of broth before adding more. Stir often and cook until the risotto is al dente and creamy, not mushy.', 'Add the mushroom mixture back into the rice.', 'Stir in Parmesan and peas then garnish with parsley. Serve warm.']
r7 = Recipe.create :dish => 'Piri-Piri Chicken bake', :image => 'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/piri-piri-chicken-with-smashed-sweet-potatoes-broccoli-84cb220.jpg?quality=90&webp=true&resize=440,400', :serves => 3, :time => 60, :ingredients => ['3 large sweet potatoes (about 900g), peeled and cut into large chunks', 'oil , for drizzling', '6-8 chicken thighs, skin left on', '2 red onions, cut into wedges', '25g sachet piri-piri spice mix', '300g long-stem broccoli'], :method => ["STEP 1. Heat the oven to 180C/160C fan/gas 4. Toss the sweet potatoes with a generous drizzle of oil and some seasoning, and tip into a very large roasting tin. Push the potatoes to one end of the tin, then, in the other end, toss the chicken with the onions, spice mix, a drizzle of oil and some seasoning. Roast for 40 mins, stirring everything halfway through. Add the broccoli to the tin, drizzle with a little oil and season, then roast for 10-15 mins more.", "STEP 2. Remove the chicken, onions and broccoli from the tin. Roughly mash the potatoes using a fork, making sure you incorporate all the chicken juices and spices from the pan. Spread the mash over the base of the tin, then top with the broccoli, chicken and onions and serve from the tin in the middle of the table."]
r8 = Recipe.create :dish => 'Rocky Road', :image => 'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/easy-rocky-road-13bd3fb.jpg?quality=90&webp=true&resize=440,400', :serves => 12, :time => 20, :ingredients => ['200g digestive biscuits', '135g butter', '200g dark chocolate', '2-3 tbsp golden syrup', '100g mini marshmallows', 'icing sugar, to dust'], :method => ["STEP 1 Grease and line an 18cm square brownie tin with baking paper.", "STEP 2 Place 200g digestive biscuits in a freezer bag and bash with a rolling pin or just the side of your fist until they're broken into a mixture of everything between dust and 50p-sized lumps. Set aside.", "STEP 3 In a large saucepan melt 135g butter or margarine, 200g dark chocolate and 2-3 tbsp golden syrup over a gentle heat stirring constantly until there are no or almost no more lumps of chocolate visible, then remove from the heat. Leave to cool.", "STEP 4 Take the biscuits, 100g mini marshmallows and up to 100g of additional ingredients (dried fruit, nuts, popcorn, honeycomb), if you like, and stir into the chocolate mixture until everything is completely covered.", 'STEP 5 Tip the mixture into the lined baking tin, and spread it out to the corners. Chill for at least 2 hrs then dust with icing sugar and cut into 12 fingers.']

Cookbook.destroy_all
c1 = Cookbook.create :title => 'mybreakfast'
c2 = Cookbook.create :title => 'bananarama'
puts "#{ Cookbook.count } cookbooks created."

puts "User and recipes"
u1.recipes << r1 << r2
u2.recipes << r3 << r4

puts "Cookbooks and recipes"
c1.recipes << r1 << r2 << r3
c2.recipes << r3 << r4

puts "Recipes and cookbooks"
r1.cookbooks << c1 << c2
r2.cookbooks << c1
r3.cookbooks << c1 << c2
r4.cookbooks << c1 << c2

puts "User and cookbooks"
u1.cookbooks << c1
u2.cookbooks << c2
